#!/bin/bash
#
#	wgetx  - Downloads a directory from a website to the current directory
#
#
#    IE6 on Windows XP: Mozilla/4.0 (compatible; MSIE 6.0; Microsoft Windows NT 5.1) 
#    Firefox on Windows XP: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14 
#    Firefox on Ubuntu Gutsy: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.14) Gecko/20080418 Ubuntu/7.10 (gutsy) Firefox/2.0.0.14 
#    Safari on Mac OS X Leopard: Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en) AppleWebKit/523.12.2 (KHTML, like Gecko) Version/3.0.4 Safari/523.12.2    
#
#
#
#
#
#

#     USER AGENT
#	

FIREFOX_WINDOWS="Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14"

AGENT1="$FIREFOX_WINDOWS"

wget -b -c -nd -nH -l 1 -np  -k -r -U "$AGENT1" "$1"

tail -f wget-log
